"""baseline schema"""
revision = 'e9590e6a671d'
down_revision = None
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('actor_id', sa.String(length=36), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('entity_type', sa.String(length=80), nullable=False),
    sa.Column('entity_id', sa.String(length=80), nullable=True),
    sa.Column('outcome', sa.String(length=30), nullable=False),
    sa.Column('details', sa.JSON(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_events_action'), 'audit_events', ['action'], unique=False)
    op.create_index(op.f('ix_audit_events_actor_id'), 'audit_events', ['actor_id'], unique=False)
    op.create_index(op.f('ix_audit_events_occurred_at'), 'audit_events', ['occurred_at'], unique=False)
    op.create_table('organizations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('level', sa.Enum('NATIONAL', 'STATE', 'DISTRICT', name='orglevel'), nullable=False),
    sa.Column('state', sa.String(length=80), nullable=True),
    sa.Column('district', sa.String(length=100), nullable=True),
    sa.Column('parent_id', sa.String(length=36), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organizations_district'), 'organizations', ['district'], unique=False)
    op.create_index(op.f('ix_organizations_name'), 'organizations', ['name'], unique=True)
    op.create_index(op.f('ix_organizations_state'), 'organizations', ['state'], unique=False)
    op.create_table('projects',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=240), nullable=False),
    sa.Column('state', sa.String(length=80), nullable=False),
    sa.Column('district', sa.String(length=100), nullable=False),
    sa.Column('location', sa.String(length=160), nullable=False),
    sa.Column('category', sa.String(length=80), nullable=False),
    sa.Column('agency', sa.String(length=180), nullable=False),
    sa.Column('vendor_name', sa.String(length=180), nullable=True),
    sa.Column('sanctioned_lakh', sa.Float(), nullable=False),
    sa.Column('spent_lakh', sa.Float(), nullable=False),
    sa.Column('physical_progress', sa.Integer(), nullable=False),
    sa.Column('peer_median_lakh', sa.Float(), nullable=True),
    sa.Column('sanction_date', sa.Date(), nullable=False),
    sa.Column('planned_completion_date', sa.Date(), nullable=False),
    sa.Column('last_evidence_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('risk_score', sa.Integer(), nullable=False),
    sa.Column('risk_level', sa.Enum('CRITICAL', 'HIGH', 'MODERATE', 'LOW', name='risklevel'), nullable=False),
    sa.Column('risk_reasons', sa.JSON(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_projects_category'), 'projects', ['category'], unique=False)
    op.create_index(op.f('ix_projects_district'), 'projects', ['district'], unique=False)
    op.create_index('ix_projects_risk', 'projects', ['risk_level', 'risk_score'], unique=False)
    op.create_index('ix_projects_scope', 'projects', ['state', 'district'], unique=False)
    op.create_index(op.f('ix_projects_state'), 'projects', ['state'], unique=False)
    op.create_index(op.f('ix_projects_status'), 'projects', ['status'], unique=False)
    op.create_index(op.f('ix_projects_title'), 'projects', ['title'], unique=False)
    op.create_index(op.f('ix_projects_vendor_name'), 'projects', ['vendor_name'], unique=False)
    op.create_table('alerts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=32), nullable=False),
    sa.Column('rule_code', sa.String(length=80), nullable=False),
    sa.Column('title', sa.String(length=180), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=False),
    sa.Column('severity', sa.Enum('CRITICAL', 'HIGH', 'MODERATE', 'LOW', name='risklevel'), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('confidence', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'TRIAGED', 'RESOLVED', 'DISMISSED', name='alertstatus'), nullable=False),
    sa.Column('recommended_action', sa.Text(), nullable=False),
    sa.Column('evidence', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'rule_code', 'status', name='uq_active_rule_alert')
    )
    op.create_index(op.f('ix_alerts_project_id'), 'alerts', ['project_id'], unique=False)
    op.create_index(op.f('ix_alerts_rule_code'), 'alerts', ['rule_code'], unique=False)
    op.create_index(op.f('ix_alerts_severity'), 'alerts', ['severity'], unique=False)
    op.create_index(op.f('ix_alerts_status'), 'alerts', ['status'], unique=False)
    op.create_table('risk_snapshots',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=32), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('level', sa.Enum('CRITICAL', 'HIGH', 'MODERATE', 'LOW', name='risklevel'), nullable=False),
    sa.Column('reasons', sa.JSON(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_risk_snapshots_project_id'), 'risk_snapshots', ['project_id'], unique=False)
    op.create_index('ix_risk_snapshots_project_recorded', 'risk_snapshots', ['project_id', 'recorded_at'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('full_name', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('MINISTRY', 'STATE', 'DISTRICT', 'AUDITOR', 'FIELD_OFFICER', 'MP', name='role'), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('token_version', sa.Integer(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_organization_id'), 'users', ['organization_id'], unique=False)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.create_table('inspection_evidence',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=32), nullable=False),
    sa.Column('submitted_by', sa.String(length=36), nullable=False),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('reported_progress', sa.Integer(), nullable=False),
    sa.Column('remarks', sa.Text(), nullable=False),
    sa.Column('distance_from_project_km', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['submitted_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_inspection_evidence_project_captured', 'inspection_evidence', ['project_id', 'captured_at'], unique=False)
    op.create_index(op.f('ix_inspection_evidence_project_id'), 'inspection_evidence', ['project_id'], unique=False)
    op.create_index(op.f('ix_inspection_evidence_submitted_by'), 'inspection_evidence', ['submitted_by'], unique=False)
    op.create_table('investigation_cases',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('alert_id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=180), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'INVESTIGATING', 'CLOSURE_REVIEW', 'CLOSED', name='casestatus'), nullable=False),
    sa.Column('priority', sa.Enum('CRITICAL', 'HIGH', 'MODERATE', 'LOW', name='risklevel'), nullable=False),
    sa.Column('owner_id', sa.String(length=36), nullable=True),
    sa.Column('created_by', sa.String(length=36), nullable=False),
    sa.Column('closure_note', sa.Text(), nullable=True),
    sa.Column('closed_by', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['alert_id'], ['alerts.id'], ),
    sa.ForeignKeyConstraint(['closed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('alert_id', name='uq_case_alert')
    )
    op.create_index('ix_cases_project_status', 'investigation_cases', ['project_id', 'status'], unique=False)
    op.create_index(op.f('ix_investigation_cases_alert_id'), 'investigation_cases', ['alert_id'], unique=True)
    op.create_index(op.f('ix_investigation_cases_closed_by'), 'investigation_cases', ['closed_by'], unique=False)
    op.create_index(op.f('ix_investigation_cases_created_by'), 'investigation_cases', ['created_by'], unique=False)
    op.create_index(op.f('ix_investigation_cases_owner_id'), 'investigation_cases', ['owner_id'], unique=False)
    op.create_index(op.f('ix_investigation_cases_project_id'), 'investigation_cases', ['project_id'], unique=False)
    op.create_index(op.f('ix_investigation_cases_status'), 'investigation_cases', ['status'], unique=False)
    op.create_table('refresh_sessions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('replaced_by', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_index(op.f('ix_refresh_sessions_user_id'), 'refresh_sessions', ['user_id'], unique=False)
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_refresh_sessions_user_id'), table_name='refresh_sessions')
    op.drop_table('refresh_sessions')
    op.drop_index(op.f('ix_investigation_cases_status'), table_name='investigation_cases')
    op.drop_index(op.f('ix_investigation_cases_project_id'), table_name='investigation_cases')
    op.drop_index(op.f('ix_investigation_cases_owner_id'), table_name='investigation_cases')
    op.drop_index(op.f('ix_investigation_cases_created_by'), table_name='investigation_cases')
    op.drop_index(op.f('ix_investigation_cases_closed_by'), table_name='investigation_cases')
    op.drop_index(op.f('ix_investigation_cases_alert_id'), table_name='investigation_cases')
    op.drop_index('ix_cases_project_status', table_name='investigation_cases')
    op.drop_table('investigation_cases')
    op.drop_index(op.f('ix_inspection_evidence_submitted_by'), table_name='inspection_evidence')
    op.drop_index(op.f('ix_inspection_evidence_project_id'), table_name='inspection_evidence')
    op.drop_index('ix_inspection_evidence_project_captured', table_name='inspection_evidence')
    op.drop_table('inspection_evidence')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_index(op.f('ix_users_organization_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index('ix_risk_snapshots_project_recorded', table_name='risk_snapshots')
    op.drop_index(op.f('ix_risk_snapshots_project_id'), table_name='risk_snapshots')
    op.drop_table('risk_snapshots')
    op.drop_index(op.f('ix_alerts_status'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_severity'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_rule_code'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_project_id'), table_name='alerts')
    op.drop_table('alerts')
    op.drop_index(op.f('ix_projects_vendor_name'), table_name='projects')
    op.drop_index(op.f('ix_projects_title'), table_name='projects')
    op.drop_index(op.f('ix_projects_status'), table_name='projects')
    op.drop_index(op.f('ix_projects_state'), table_name='projects')
    op.drop_index('ix_projects_scope', table_name='projects')
    op.drop_index('ix_projects_risk', table_name='projects')
    op.drop_index(op.f('ix_projects_district'), table_name='projects')
    op.drop_index(op.f('ix_projects_category'), table_name='projects')
    op.drop_table('projects')
    op.drop_index(op.f('ix_organizations_state'), table_name='organizations')
    op.drop_index(op.f('ix_organizations_name'), table_name='organizations')
    op.drop_index(op.f('ix_organizations_district'), table_name='organizations')
    op.drop_table('organizations')
    op.drop_index(op.f('ix_audit_events_occurred_at'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_actor_id'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_action'), table_name='audit_events')
    op.drop_table('audit_events')
    # ### end Alembic commands ###
